name: Get Key Vault Secret

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  get-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: 8d89c850-b5d0-470a-8b73-4a86f654d0a1
        tenant-id: b11d4762-e403-429c-8a6e-6d29aaccb759
        allow-no-subscriptions: true

    - name: Retrieve Secret
      run: |
        az keyvault secret show \
          --vault-name FedTest-kv01 \
          --name FedKVSecret \
          --query value -o tsv
